- .github/workflows/chromatic.yml
- package.json
- Closed #35 
- `.github/workflows/chromatic.yml` 파일 추가
- github action으로 dev브랜치 최신화마다 스토리북도 자동 배포가 되도록 하는 설정파일입니다.
> chore: 스토리북 지속 배포를 위한 chromatic.yml 파일 추가

- app/components/InputField.tsx
- stories/Input.stories.tsx
스크럼 때 말씀해주신 인풋필드를 수정했습니다.
요구해주신게 이게 맞으실까요...?
- 에러메세지가 props로 주어지면 렌더링 될 때 반영하도록 수정했습니다.
- 기존에는 validator가 있을 때 Blur 이벤트에서 유효성 검사를 했는데 이를 분리해 validator를 쓰지 않을 경우에도 에러메세지를 출력하게 변경했습니다.
-
> feat/#11--공통-인풋 - 에러 방식 변경

- app/components/Loading/index.tsx
- app/components/icons/LoadIcon.tsx
- app/dummy/layout.tsx
- app/dummy/loading/page.tsx
- app/dummy/page.tsx
- app/styles/globals.css
- stories/Loading.stories.ts
- stories/Modal.stories.ts
- Closed #56 
- 로드 아이콘 추가
- 로딩 컴포넌트 추가
- 로딩 컴포넌트 스토리 페이지 추가
- 임의로 간단하게 만들었어요.
- 아이콘만 써도 잘 돌아 갑니다.
- 제멋대로 만든거라 언제든 디자인이든, 어떤 거든 수정 요청 환영합니다.
- 기본
> Feat/#56 로드아이콘 로딩 컴포넌트

- app/[teamid]/modify/page.tsx
- app/addteam/layout.tsx
- app/addteam/page.tsx
- app/components/Button.tsx
- app/invitation/page.tsx
- app/styles/team.module.css
- Closed #63 
- 팀 생성, 수정, 참여 페이지 퍼블리싱 완료
- 아직 기능은 작동하지 않습니다.
- ui 확인용 코드 조금 들어가 있습니다.
> Feat/#63 팀 생성 수정 참여 페이지 퍼블

- app/components/Button.tsx
- app/dummy/button/page.tsx
- app/dummy/layout.tsx
- stories/Button.stories.tsx
- Closed #70 
- 공용 버튼 컴포넌트에 링크 속성 추가
- /dummy/button과 스토리북에 간단한 예시를 추가해뒀습니다.
- ![image](https://github.com/user-attachments/assets/da7e41b2-2ec9-446a-a4be-08a633d2ee53)
> feat: 버튼 컴포넌트 링크 속성 추가

- app/[teamid]/modify/page.tsx
- app/[teamid]/page.tsx
- app/components/ImageUpload.tsx
- app/dummy/page.tsx
- app/not-found.tsx
- next.config.ts
- Closed #73 
- not-found 디자인 수정
- 더미(`/dummy`) 페이지 개발 환경에서만 접근 가능하도록 수정
- 이미지 업로드 컴포넌트 초기 이미지 파일 주소값 받아서 보여지도록 수정
- 이미지 업로드 컴포넌트 Image에 layout, object 속성 대신 클래스 적용
- 팀 수정 페이지 기능 작업
- 기능만 수정해서 이미지는 따로 첨부하지 않았습니다.
-
> Feat/#73 팀 수정 페이지 기능

- app/components/Modal/Modal.module.css
- app/components/Modal/index.tsx
- app/dummy/layout.tsx
- app/dummy/modal/page.tsx
- tailwind.config.ts
- Closed #86 
- 위치문제를 position 속성 추가하여 해결
- 더미 페이지 레이아웃도 반응형 작업함
- tailwind설정에 필요없는 부분 발견하여 삭제
- 모달에 `position` 속성이 추가 되었고, 기본 값은 `center`입니다.
- 상단에 나오게 하거나, 모달의 크기가 스크롤 되야할 정도를 클 때는 `top` 값으로 설정해서 사용하세요.
-
> Fix/#86 모달 위치 문제 및 기타 해결

- app/boards/BestCardList.tsx
- app/boards/CardList.tsx
- app/boards/SearchBar.tsx
- app/boards/[articleId]/Comments.tsx
- app/boards/[articleId]/page.tsx
- app/boards/write/page.tsx
- app/constants/form.ts
- Closed #105
- CardList 컴포넌트에 "검색 결과가 없습니다." 문구만 추가했습니다..! 연산자가 추가돼서 그런지 엄청 많이 수정된 거처럼 보이네요... 
-
> Feat/105  자유게시판 개선작업

- app/[teamid]/MemberList.tsx
- app/[teamid]/TaskLists.tsx
- app/[teamid]/modify/page.tsx
- app/[teamid]/page.tsx
- app/addteam/page.tsx
- app/layout.tsx
- app/styles/globals.css
- package-lock.json
- package.json
- Closed #123 
- 토스트 플러그인 추가
- 설정 및 테스트
- 스타일 수정
- 토스트 적용
- 토스트 플러그인을 추가하고 원 디자인에 맞게 수정하였습니다.
- `layout.tsx`에 `ToastContainer` 추가해 두었으니 사용하실 땐 `toast`만 import 하셔서 호출하시면 됩니다.
```js
// 호출할 곳에서
toast('기본 텍스트');
toast.success('성공 텍스트');
toast.error('실패 텍스트');
```
- 참조: https://fkhadra.github.io/react-toastify/introduction
> feat/#123-토스트 추가 설정 및 테스트

- tsconfig.json
- Closed #127
- `tsconfig.json` 에 절대 경로 추가
- `@stores`
- `@types`
- `@constants`
- `@api`
- 절대 경로 정의가 되어있지 않은 추가된 폴더들의 경로를 정의하였습니다.
- import 구문 리팩토링 작업을 하실 때, 현재 사용 중인 상대 경로를 절대 경로로 변경하는 작업도 같이 진행해주시면 될 것 같습니다.
> chore/127--절대 경로 추가

- app/myhistory/LoadingMyhistory.tsx
- app/myhistory/layout.tsx
- app/myhistory/page.tsx
- Closed #124
- 마이히스토리 스켈레톤 추가
- 자유게시판과 통일성을 주기 위해 animate-pulse만 추가하고 따로 추가 애니메이션을 넣지는 않았습니다
- 코드가 길진 않아서 그냥 리턴문에 넣었는데 분리하는게 맞는 것 같기도 해서 의견 주시면 감사하겠습니다
- 스켈레톤을 넣는 경우 데이터 받아오는 속도가 빠르면 깜빡이는 것 처럼 느껴질 수 있다고 하는데 한번 보시고 지연처리가 필요할 것 같으면 말씀해주세요 수정하겠습니다!
https://github.com/user-attachments/assets/51b004b8-daac-4b05-84f9-cf23e192b3e2
> Feat/#124  마이히스토리 스켈레톤

- app/boards/BestCardList.tsx
- app/boards/CardList.tsx
- app/boards/LikeButton.tsx
- app/boards/Pagination.tsx
- app/boards/PostActionDropdown.tsx
- app/boards/[articleId]/Comments.tsx
- app/boards/[articleId]/page.tsx
- app/boards/page.tsx
- app/boards/write/page.tsx
- app/constants/form.ts
- Closed #136 
- 로그아웃 상태일 때 특정 페이지 접근 막는 건 공통으로 뺄 가능성이 있어 보여서 안 했습니다!
- 토스트는 그냥 제가 토스트 메세지로 어울리는 부분을 설정해놨는데... 다른 부분도 어울리는 거 같다 싶으면 말씀해주세요!
> Feat/136  자유게시판 qa반영

- app/components/Gnb/ProfileDropDown.tsx
- app/components/Gnb/TeamListDropDown.tsx
- app/components/Gnb/TeamListDropDownItem.tsx
- app/components/Gnb/TeamListSideBar.tsx
- app/components/Gnb/index.tsx
- app/layout.tsx
- tsconfig.json
- Closed #138 
- 사이드바 팀 생성 버튼 추가
- 팀 생성 페이지 이동 시 드롭다운 닫기
- 사이드 버튼 스타일 수정
- 팀 이름 `truncate` 적용 길이 축소
- 사용자 이미지 추가
- QA 바탕으로 수정하고, 기존 수정이 필요했던 부분들도 함께 수정했습니다.
- 사용자 이미지가 설정된 경우, 사용자 이미지가 기존 프로필 이미지를 대체하도록 추가했습니다.
- path 순서를 조정했는데, `@`와 `@app`의 순서를 또 잘못 설정해서.. 여기서 다시 수정했습니다. 이제 정말로 자동완성으로 '@app`으로 시작하는 경로가 입력될 겁니다..! 적용 안 된다면 에디터를 재실행해주세요!
> Refactor/138  gnb 기능개선 리팩토링

- app/components/Gnb/ProfileDropDown.tsx
- app/components/Gnb/TeamListDropDown.tsx
- app/components/Gnb/TeamListDropDownItem.tsx
- app/components/Gnb/index.tsx
- #138
- 비 로그인 시에도 자유게시판 메뉴 표시
- gnb 로고 경고 제거
- 사용자 프로필 스타일 수정
- 드롭다운 반응형 스타일 수정
- 추가하기로 한 기능 추가하고, 이미지 경고 제거했습니다.
- 팀 리스트 드롭다운의 글자 크기를 반응형에 알맞게 일부 수정했습니다.
> Refactor/138  gnb 기능개선 리팩토링 (2차 작업)

- app/noteam/page.tsx
- Closed #141
- 하단 여백 없음 수정
- 로그인상태 아닐 시, 팀 있는 경우 리다이렉트 추가
- 따로 에러 메시지 없이 페이지 이동하도록 설정했는데 괜찮을지 검토부탁드립니다
-
> Refactor/#141  noteam 리팩토링

- app/[teamid]/modify/page.tsx
- app/[teamid]/page.tsx
- app/components/Modal/AlertModal.tsx
- app/invitation/page.tsx
- Closed #164 
- `AlertModalOpen` 함수 두번째 파라미터 옵션으로 수정
- 팀 수정 페이지 관리자 여부 확인 처리
- `AlertModalOpen` 함수가 제 의도와 다르게 두번째 파라미터가 필수 이길래 옵션으로 바꿨습니다.
- 팀 수정 페이지 접근시 관리자 여부를 확인하는 처리를 추가하였습니다.
-
> Fix/#164 팀페이지 qa 추가 적용

- app/[teamid]/tasklist/task-detail/CheckButton.tsx
- app/components/Landing/Section1.tsx
- app/components/Landing/Section2.tsx
- app/components/Landing/Section3.tsx
- app/components/Landing/ServiceIntro.tsx
- app/components/Landing/ServiceOutro.tsx
- app/myhistory/DailyItemList.tsx
- app/myhistory/FilterDropdown.tsx
- app/myhistory/page.tsx
- app/noteam/page.tsx
- Closed #173
- 리스트 상세 완료 체크해제or체크 시 히스토리 갱신되도록 수정
- import 컨벤션 수정
- 리액트 쿼리로 변경하면서 완료 체크 변동 시 히스토리 갱신이 되지 않는 부분 수정했습니다
+) 빌드 에러는 github action 에러인걸로 확인됩니다. 딱 오늘부터 이전 패키지가 종료되었군요..
> Fix/#173  마이히스토리 리스트 동기화

- app/noteam/page.tsx
- Closed #176
- import 컨벤션 수정
- 유저 없을 때 페이지 이동 제거
- 이미 참여한 팀 있을 때 모달 추가
- 페이지 리다이렉트 전에 보여주는 모달만 추가했습니다
- 이미 참여한 팀 있는 경우
> refactor/#176 noteam 개선

- stories/CustomCalendar.stories.tsx
- Closed #188 
- 스토리북에 커스텀캘린더를 추가했습니다.
- 
- ![image](https://github.com/user-attachments/assets/c4e08c2d-bde7-4c18-93ad-509ba802943d)
> feat: 캘린더 스토리북 추가

- stories/CircleGraph.stories.ts
- Closed #187 
- 그래픽 컴포넌트 스토리북에 추가
- 도넛 모양 컴포넌트 스토리북에 추가 했습니다.
- 로딩 컴포넌트는 진즉에 스토리북에 올려놨었는데 까먹고 있었네요. ㅎ
> docs/#187 스토리북 컴포넌트 추가

- package-lock.json
- package.json
- stories/GNB.stories.tsx
- Closed #192 
- gnb 비로그인 상태 스토리 추가
- jest 라이브러리 제거
- 로그인 상태와 비 로그인 상태를 각각 추가해보려고 했는데, 목데이터로 전역 상태 등을 설정해줘도 gnb 안에 훅이 너무 많아서 여러 Context, Provider 설정이 너무 복잡해졌습니다. 그래서 비 로그인만 추가했고, 사이드바가 있음을 알릴 수 있게 데스크탑과 모바일 각각 추가했습니다.
> docs/ gnb 비로그인 스토리 파일 추가
